"""Initial migration.

Revision ID: 0708b4a0f2c2
Revises: 5b6a637ca8e5
Create Date: 2024-02-10 17:54:31.189159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0708b4a0f2c2'
down_revision = '5b6a637ca8e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('charactername', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('charactername')

    # ### end Alembic commands ###
