"""Initial migration

Revision ID: 1bbd7b82303b
Revises: 
Create Date: 2024-05-19 00:30:21.709161

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1bbd7b82303b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pomodorostats')
    with op.batch_alter_table('pomodoro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('end_time', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('duration', sa.Interval(), nullable=True))
        batch_op.add_column(sa.Column('pomodoro_time_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=False))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('date_completed')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pomodoro_time_count_alltime', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('pomodoro_time_count_alltime')

    with op.batch_alter_table('pomodoro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_completed', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('date')
        batch_op.drop_column('completed')
        batch_op.drop_column('pomodoro_time_count')
        batch_op.drop_column('duration')
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')

    op.create_table('pomodorostats',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='pomodorostats_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='pomodorostats_pkey')
    )
    # ### end Alembic commands ###
