"""Added wallpaper field to User model

Revision ID: 47863e1f344d
Revises: 66a25b5a9bb8
Create Date: 2024-02-03 17:52:57.594822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47863e1f344d'
down_revision = '66a25b5a9bb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notecontent', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('notecontent')

    # ### end Alembic commands ###
