"""Initial migration.

Revision ID: 5b6a637ca8e5
Revises: 4f9ceedc09fb
Create Date: 2024-02-10 17:43:02.908083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b6a637ca8e5'
down_revision = '4f9ceedc09fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pomodoro_time_count', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('pomodoro_time_count')

    # ### end Alembic commands ###
