"""Added wallpaper field to User model

Revision ID: 66a25b5a9bb8
Revises: af9e6e145d67
Create Date: 2024-02-03 17:34:56.331990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66a25b5a9bb8'
down_revision = 'af9e6e145d67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wallpaper', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('wallpaper')

    # ### end Alembic commands ###
