"""neu

Revision ID: 6e29e92b571d
Revises: 8e4791830fe4
Create Date: 2024-02-06 12:59:54.622272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e29e92b571d'
down_revision = '8e4791830fe4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('taskname', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('totalPomodoros', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('completedPomodoros', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('completedPomodoros')
        batch_op.drop_column('totalPomodoros')
        batch_op.drop_column('taskname')

    op.create_table('task',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('totalPomodoros', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('completedPomodoros', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_username', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_username'], ['user.username'], name='task_user_username_fkey'),
    sa.PrimaryKeyConstraint('id', name='task_pkey')
    )
    # ### end Alembic commands ###
