"""Initial migration.

Revision ID: 8e4791830fe4
Revises: aac2a3471c6e
Create Date: 2024-02-06 12:51:35.149460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e4791830fe4'
down_revision = 'aac2a3471c6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_username', sa.String(length=100), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_username'], ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_username')

    # ### end Alembic commands ###
